import type { Metadata } from "next";
import { Inter, Roboto_Serif, Work_Sans } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer/page";
const inter = Inter({ subsets: ["latin"] });
const work_sans = Work_Sans({ subsets: ["latin"], variable: "--font-work" });
const roboto = Roboto_Serif({ subsets: ["latin"], variable: "--font-roboto" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${work_sans.variable} ${roboto.variable}`}>
        {children}
      </body>
      <Footer />
    </html>
  );
}
