import type { Metadata } from "next";
import { Inter, Roboto_Serif, Work_Sans } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer/footer"
const inter = Inter({ subsets: ["latin"] });
const work_sans = Work_Sans({ subsets: ['latin']});
const roboto = Roboto_Serif({ subsets:['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'${inter.className} ${work_sans.className} ${roboto.className}'}>
        {children}</body>
      <Footer/>
    </html>
  );
}
